--Get system date. 

SELECT GETDATE();


--Get UTC date. 

SELECT GETUTCDATE();


--. Get the first name, current date, joiningdate and diff between current date and joining date in months. 

SELECT * FROM EMPLOYEE1;

SELECT FIRSTNAME,GETDATE() AS CURRENTDATE,JOININGDATE,DATEDIFF(MONTH,JOININGDATE,GETDATE()) AS NOOFMONTHS FROM EMPLOYEE1;

SELECT FIRSTNAME,GETDATE() AS CURRENTDATE,JOININGDATE,DATEDIFF(MM,JOININGDATE,GETDATE()) AS NOOFMONTHS FROM EMPLOYEE1;


--26). Get the first name, current date, joiningdate and diff between current date and 
--joining date in days. 

SELECT FIRSTNAME,GETDATE() AS CURRENTDATE,JOININGDATE,DATEDIFF(DD,JOININGDATE,GETDATE()) AS NOOFDAYS FROM EMPLOYEE1;

SELECT FIRSTNAME,GETDATE() AS CURRENTDATE,JOININGDATE,DATEDIFF(DAY,JOININGDATE,GETDATE()) AS NOOFDAYS FROM EMPLOYEE1;

