SELECT * FROM EMPLOYEE1;

SELECT DISTINCT(DEPARTMENT) FROM EMPLOYEE1;

SELECT MAX(SALARY) FROM EMPLOYEE1;

SELECT MIN(SALARY) FROM EMPLOYEE1;


SELECT CONVERT(VARCHAR(20),JOININGDATE,106) AS NEWDATE FROM EMPLOYEE1;


SELECT CONVERT(VARCHAR(20),JOININGDATE,111) AS NEWDATE FROM EMPLOYEE1;

SELECT CONVERT(VARCHAR(20),JOININGDATE,108) AS NEWDATE FROM EMPLOYEE1;