use amazon_db; 
SELECT * FROM CUSTOMER_TB; 
#INSERT THE RECORDS



#INSERT STATEMNT(INSERT-->FIRSTTIME/NEW RECORDS)
#UPDATE STATEMENT(UPDATE-->FOR EXISTING RECORDS)---->TO UPDATE THE RECORDS
#DELETE STATEMENT(DELETE-->DELETE FOR EXISTING RECORDS)
#ALTER STATEMENT(ALTER-->ALTERING THE EXSTING TABLE)----->ALTER THE TABLE FEATURES/COLUMNS)

DROP TABLE CUSTOMER_TB;

CREATE TABLE CUSTOMER_TB(
CUST_NAME CHAR(20),
CUST_AGE INT,
CUST_PHON INT,
CUST_LOC CHAR(30)
);

INSERT INTO CUSTOMER_TB VALUES("SAM",30,1234567890,'BANGALORE');
INSERT INTO CUSTOMER_TB VALUES("HARI",30,1689543567,'CHENNAI');
INSERT INTO CUSTOMER_TB VALUES("HEMA",NULL,123478902,'HYD');
INSERT INTO CUSTOMER_TB(CUST_NAME,CUST_LOC) VALUES("DIVI",'MUMBAI');
INSERT INTO CUSTOMER_TB(CUST_NAME,CUST_AGE,CUST_PHON,CUST_LOC) VALUES("RAHUL",33,123458907,'DELHI');

SET SQL_SAFE_UPDATES=0;  #TELLING MYSQL PLS ALLOW ME TO RUN UPDATE/DELETE.YES I KNOW WHAT IS GOING TO HAPPENED

#UPDATE STATEMENT WITHOUT WHERE CONDITION IS VERY RISKY TO RUN#

UPDATE CUSTOMER_TB SET CUST_LOC='KOTCHI' WHERE CUST_NAME='SAM';
UPDATE CUSTOMER_TB SET CUST_AGE=29 WHERE  CUST_NAME='HEMA';
UPDATE CUSTOMER_TB SET CUST_AGE=28,CUST_PHON=112345678 WHERE  CUST_NAME='DIVI';
UPDATE CUSTOMER_TB SET CUST_LOC='GOA';#VERY RISKY

#DELETE STATEMENT WITHOUT WHERE CONDITION IS VERY RISKY TO RUN#
DELETE FROM CUSTOMER_TB WHERE CUST_NAME='SAM';
DELETE FROM CUSTOMER_TB; #VERY RISKY

ALTER TABLE CUSTOMER_TB ADD COLUMN CUST_EMAIL CHAR(40);

UPDATE CUSTOMER_TB SET CUST_EMAIL='harim@gmail.com' WHERE CUST_NAME='HARI';

ALTER TABLE CUSTOMER_TB DROP COLUMN CUST_AGE;


