
#THIS STATMENT WE CANT ABLE TO EXECUTE BEACUSE WE DONT HAVE USER ARUN AND WE ARE USING DEVELOPER VERSION (INDIVIDUAL SYSTEM)
GRANT SELECT ON STUDENT_DETAILS TO ARUN;
GRANT INSERT ON STUDENT_DETAILS TO ARUN;


REVOKE SELECT ON STUDENT_DETAILS FROM ARUN;
REVOKE INSERT ON STUDENT_DETAILS FROM ARUN;

GRANT SELECT (TRAINER_ID,TRAINER_NAME,TRAINER_EXP) ON STUDENT_DETAILS TO ARUN; #HIDE THE TRAINER_SALARY COLUMN