
USE AMAZON_DB;
DROP TABLE TCL_TB;
CREATE TABLE TCL_TB(
ID INT,
NAME VARCHAR(20),
AGE INT
);


SELECT * FROM TCL_TB;
INSERT INTO TCL_TB VALUES(1,'RAJU',25);
INSERT INTO TCL_TB VALUES(2,'ANIL',26);
INSERT INTO TCL_TB VALUES(3,'RAMU',24);
INSERT INTO TCL_TB VALUES(4,'ANAD',22);
INSERT INTO TCL_TB VALUES(5,'HARI',20);
SET SQL_SAFE_UPDATES=0; 
SET AUTOCOMMIT=0;  # I AM TELLING MY MYSQL,PLS WAIT UNTIL I CONFIRM(COMMIT)

START TRANSACTION; #START CODE
DELETE FROM TCL_TB;
SELECT * FROM TCL_TB;
ROLLBACK;
SELECT * FROM TCL_TB;


START TRANSACTION; 
UPDATE TCL_TB SET AGE=99 WHERE NAME='RAJU';
UPDATE TCL_TB SET AGE=99 WHERE NAME='ANIL';
SELECT * FROM TCL_TB;
ROLLBACK;
SELECT * FROM TCL_TB;

START TRANSACTION;
SAVEPOINT A;
SELECT * FROM TCL_TB;
INSERT INTO TCL_TB VALUES(6,'NEW PERSON',25);
SELECT * FROM TCL_TB;
SAVEPOINT B;
UPDATE TCL_TB SET AGE=99 WHERE NAME='RAMU';
SELECT * FROM TCL_TB;
SAVEPOINT C;
DELETE FROM TCL_TB WHERE ID=1;
DELETE FROM TCL_TB WHERE ID=2;
DELETE FROM TCL_TB WHERE ID=3;
ROLLBACK TO C;
SELECT * FROM TCL_TB;

START TRANSACTION;
SELECT * FROM TCL_TB;
UPDATE TCL_TB SET AGE=100 WHERE ID=1;
UPDATE TCL_TB SET AGE=100 WHERE ID=2;
SELECT * FROM TCL_TB;
COMMIT; #CONFIRMED TO DATABASE.TELLING THAT...THIS IS CORRECT
UPDATE TCL_TB SET AGE=100 WHERE ID=3;
UPDATE TCL_TB SET AGE=100 WHERE ID=4;
SELECT * FROM TCL_TB;
ROLLBACK;
SELECT * FROM TCL_TB;


SELECT * FROM TCL_TB;
START TRANSACTION;
SAVEPOINT X;
ALTER TABLE TCL_TB ADD COLUMN COMPANY VARCHAR(20); #DDL
SELECT * FROM TCL_TB;
SAVEPOINT Y;
UPDATE TCL_TB SET COMPANY='TCS'; #DML
SELECT * FROM TCL_TB;
ROLLBACK TO X;
SELECT * FROM TCL_TB;








